title: Olá! Seja bem vindo ao meu repositório
description: Marcel Bittar - repositório de projetos, posts, insights sobre programação, machine learing, deep learning, python e tecnologia.

permalink: ':title/'
baseurl: "/"
url: "https://mabittar.github.io"

# Default Language
lang: pt-BR

# Author Settings
author: Marcel Bittar
author-img: photo.jpg
about-author: My passion for technology led me to a new path of knowledge the application of Python for Data Science and Algorithms for Machine Learning and Deep Learning I uses this website to track my projects, insights and toughts.
social-linkedin: marcelbittar
social-email: mabittar@github.com
social-github: mabittar
social-twitter: marcelbittar

# Disqus
discus-identifier: mabittar

# Tracker
analytics: UA-174924624-1
adsence: ca-pub-7441448290565945

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude:
  - docs/
  - tasks/
  - vendor/
