title: Olá! Seja bem vindo ao meu repositório
description: > # this means to ignore newlines until "baseurl:"
  Marcel Bittar - repositório de projetos, posts, insights sobre programação, machine learing, deep learning, python e tecnologia.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "mabittar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Marcel Bittar # add your name
author-img: photo.jpg # add your photo
about-author: My passion in technology and programming skills drive me to start a new knowledgment area in Computer Engineering. I uses this repo to track my projects. # add description
social-linkedin: marcelbittar # add your Linkedin handle
social-email: mabittar@github.com # add your Email address
social-github: mabittar # add your Github handle
social-twitter: marcelbittar # add your Twitter handle
social-facebook: # add your Facebook handle




# Disqus
discus-identifier: marcelbittar # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
